import streamlit as st

def show_dashboard():
    st.header("Writing Analytics")
    st.write("Here you can see analytics and insights generated by the AI.")

    # Example analytics
    st.subheader("Paper Quality Score")
    st.progress(85)

    st.subheader("Citation Accuracy")
    st.progress(90)

    st.subheader("Plagiarism Check")
    st.progress(95)

if __name__ == "__main__":
    show_dashboard()
